-- =====================================================
-- MIGRACIÓN 003: Tablas experiences y skills
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- 1. Tabla de Experiencia Laboral
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  date_range TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_key TEXT NOT NULL DEFAULT 'briefcase',  -- 'briefcase' | 'book' | 'laptop' | 'activity' | 'star'
  color_key TEXT NOT NULL DEFAULT 'blue',       -- 'blue' | 'purple' | 'emerald' | 'amber' | 'rose'
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Habilidades / Skills
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  icon_key TEXT NOT NULL DEFAULT 'code2',       -- 'code2' | 'smartphone' | 'database' | 'brain' | 'server'
  color_key TEXT NOT NULL DEFAULT 'blue',       -- 'blue' | 'green' | 'purple' | 'rose' | 'amber'
  items TEXT[] NOT NULL DEFAULT '{}',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =====================================================
-- Habilitar RLS
-- =====================================================
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Experiencias son públicas" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Skills son públicos" ON public.skills FOR SELECT USING (true);

-- =====================================================
-- Seed: Datos iniciales (Experiencia Laboral)
-- =====================================================
INSERT INTO public.experiences (role, company, date_range, description, icon_key, color_key, sort_order) VALUES
(
  'Docente Contratado – Programa DSI',
  'IEST Público Paucar del Sarasara',
  'Presente',
  'Docente en el programa de Computación e Informática (DSI). Formación de estudiantes en tecnologías de la información, programación y gestión de sistemas. (Plaza: 1145002 - Pausa, Ayacucho)',
  'book',
  'blue',
  1
),
(
  'Desarrollador Mobile & AI (Freelance)',
  'Proyectos Independientes',
  '2023 – Presente',
  'Desarrollo, publicación y monetización de aplicaciones en Google Play Store. Creación de ''Papa Scan'' (detección de enfermedades en hoja de papa con IA) y ''CIE-10'' (consulta de códigos médicos).',
  'laptop',
  'purple',
  2
),
(
  'Técnico de Soporte y Redes',
  'SETELSAT Consulting',
  'Ene 2023 – Dic 2023',
  'Mantenimiento preventivo y correctivo de equipos informáticos, estructuración de redes y soporte técnico especializado a usuarios.',
  'briefcase',
  'emerald',
  3
),
(
  'Soporte y Digitador SIS',
  'DISA Apurímac II',
  'Mar 2022 – Jul 2023',
  'Gestión de sistemas de información en salud, digitación de formatos SIS, y soporte técnico a los equipos de la Dirección de Salud.',
  'activity',
  'amber',
  4
);

-- =====================================================
-- Seed: Datos iniciales (Skills / Habilidades)
-- =====================================================
INSERT INTO public.skills (category, icon_key, color_key, items, sort_order) VALUES
('Frontend & Web', 'code2', 'blue', ARRAY['Next.js', 'React', 'Tailwind CSS', 'TypeScript'], 1),
('Mobile', 'smartphone', 'green', ARRAY['Android', 'Kotlin', 'Java', 'Flutter'], 2),
('Backend & DB', 'database', 'purple', ARRAY['Supabase', 'Node.js', 'SQL', 'Oracle'], 3),
('IA & Core', 'brain', 'rose', ARRAY['TensorFlow Lite', 'MediaPipe', 'Python'], 4),
('Infra & Redes', 'server', 'amber', ARRAY['Linux Kernel', 'CCNAv7', 'Git', 'Vercel'], 5);
