create table if not exists job_postings (
  id text primary key,
  title text not null,
  slug text unique not null,
  entity_name text not null,
  entity_ruc text,
  entity_verified boolean default true,
  sector_type text not null,
  region text not null,
  category text not null,
  education_level text not null,
  salary_min numeric,
  salary_max numeric,
  salary_text text not null,
  vacancies_count integer default 1,
  description text not null,
  requirements text[] default '{}',
  apply_url text not null,
  bases_pdf_url text,
  official_portal_name text,
  start_date text not null,
  end_date text not null,
  featured boolean default false,
  views_count integer default 0,
  clicks_count integer default 0,
  status text default 'Vigente',
  created_at timestamp with time zone default timezone('utc'::text, now())
);
