// fix_rls.js - Aplica políticas RLS a experiences y skills via REST API
// Esto usa el endpoint de Supabase management API para ejecutar SQL arbitrario

const https = require('https');

const SUPABASE_URL = 'https://yeeupdgjfrkkaurytyrs.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZXVwZGdqZnJra2F1cnl0eXJzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTU4NzAyNiwiZXhwIjoyMTAxMTYzMDI2fQ.Z5MFMe44MD9mi_FQMxILhLRMXcFGiz-xgZtKBFJXDp8';

// SQL commands to create RLS policies and tables if not exists
const SQL_COMMANDS = `
-- Crear tablas si no existen (idempotente)
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  date_range TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_key TEXT NOT NULL DEFAULT 'briefcase',
  color_key TEXT NOT NULL DEFAULT 'blue',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  icon_key TEXT NOT NULL DEFAULT 'code2',
  color_key TEXT NOT NULL DEFAULT 'blue',
  items TEXT[] NOT NULL DEFAULT '{}',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas si existen para evitar conflictos
DROP POLICY IF EXISTS "Experiencias son publicas" ON public.experiences;
DROP POLICY IF EXISTS "Skills son publicos" ON public.skills;

-- Crear políticas de lectura pública
CREATE POLICY "Experiencias son publicas" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Skills son publicos" ON public.skills FOR SELECT USING (true);
`;

function postSQL(sql) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ query: sql });
    const urlObj = new URL(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`);

    // Use the pg REST endpoint directly
    const reqUrl = new URL(`${SUPABASE_URL}/rest/v1/`);
    
    // We'll use fetch-like approach with https
    const options = {
      hostname: 'yeeupdgjfrkkaurytyrs.supabase.co',
      path: '/rest/v1/rpc/exec_sql',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': SERVICE_KEY,
        'Authorization': `Bearer ${SERVICE_KEY}`,
        'Content-Length': Buffer.byteLength(body)
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// Better approach: use the Supabase JS client to run raw SQL via pg
async function fixRLS() {
  console.log('🔧 Verificando y corrigiendo RLS policies...\n');
  
  const { createClient } = require('./node_modules/@supabase/supabase-js/dist/index.cjs');
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY);
  
  // Test if anon can read experiences
  const anonClient = createClient(SUPABASE_URL, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZXVwZGdqZnJra2F1cnl0eXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1ODcwMjYsImV4cCI6MjEwMTE2MzAyNn0.cCfw0F5OI7S7Xxc43wA37UiTgueNwLKCF-uCsy-bxLc');
  
  const { data: expData, error: expError } = await anonClient.from('experiences').select('*').limit(1);
  
  if (expError) {
    console.log('❌ ANON no puede leer experiences. Error:', expError.message);
    console.log('\n⚠️  Necesitas ejecutar este SQL en el Supabase SQL Editor:\n');
    console.log('---------------------------------------------------');
    console.log(SQL_COMMANDS);
    console.log('---------------------------------------------------');
    console.log('\nURL del SQL Editor:');
    console.log('https://supabase.com/dashboard/project/yeeupdgjfrkkaurytyrs/sql/new');
  } else {
    console.log('✅ ANON puede leer experiences correctamente. Filas:', expData?.length);
  }
  
  const { data: skillData, error: skillError } = await anonClient.from('skills').select('*').limit(1);
  if (skillError) {
    console.log('❌ ANON no puede leer skills. Error:', skillError.message);
  } else {
    console.log('✅ ANON puede leer skills correctamente. Filas:', skillData?.length);
  }
  
  // Also verify content with service role
  const { data: expAll } = await supabase.from('experiences').select('id, role, is_active').order('sort_order');
  const { data: skillAll } = await supabase.from('skills').select('id, category').order('sort_order');
  
  console.log('\n📋 Experiencias en DB (service role):');
  expAll?.forEach(e => console.log(`  - [${e.id}] ${e.role} (activo: ${e.is_active})`));
  
  console.log('\n🎯 Skills en DB (service role):');
  skillAll?.forEach(s => console.log(`  - [${s.id}] ${s.category}`));
}

fixRLS().catch(console.error);
