// run_migration.js - Ejecuta la migración de experiences y skills en Supabase
// Uso: node run_migration.js (desde la raíz del monorepo)
const { createClient } = require('./node_modules/@supabase/supabase-js/dist/index.cjs');

const url = 'https://yeeupdgjfrkkaurytyrs.supabase.co';
const key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZXVwZGdqZnJra2F1cnl0eXJzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTU4NzAyNiwiZXhwIjoyMTAxMTYzMDI2fQ.Z5MFMe44MD9mi_FQMxILhLRMXcFGiz-xgZtKBFJXDp8';

const supabase = createClient(url, key);

async function runMigration() {
  console.log('🚀 Iniciando migración 003: experiences & skills...\n');

  // 1. Crear tabla experiences
  console.log('📋 Creando tabla experiences...');
  const { error: e1 } = await supabase.rpc('exec_sql', {
    sql: `CREATE TABLE IF NOT EXISTS public.experiences (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      role TEXT NOT NULL,
      company TEXT NOT NULL,
      date_range TEXT NOT NULL,
      description TEXT NOT NULL,
      icon_key TEXT NOT NULL DEFAULT 'briefcase',
      color_key TEXT NOT NULL DEFAULT 'blue',
      sort_order INTEGER NOT NULL DEFAULT 0,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );`
  });
  if (e1) console.warn('  ⚠️  experiences:', e1.message);
  else console.log('  ✅ Tabla experiences OK');

  // 2. Crear tabla skills
  console.log('📋 Creando tabla skills...');
  const { error: e2 } = await supabase.rpc('exec_sql', {
    sql: `CREATE TABLE IF NOT EXISTS public.skills (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category TEXT NOT NULL,
      icon_key TEXT NOT NULL DEFAULT 'code2',
      color_key TEXT NOT NULL DEFAULT 'blue',
      items TEXT[] NOT NULL DEFAULT '{}',
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );`
  });
  if (e2) console.warn('  ⚠️  skills:', e2.message);
  else console.log('  ✅ Tabla skills OK');

  // Usamos el SDK directamente (insert) para bypass rpc si no existe
  // 3. Seed experiences
  console.log('\n🌱 Insertando experiencias...');
  const { data: existingExp } = await supabase.from('experiences').select('id').limit(1);
  if (existingExp && existingExp.length === 0) {
    const { error: e3 } = await supabase.from('experiences').insert([
      { role: 'Docente Contratado – Programa DSI', company: 'IEST Público Paucar del Sarasara', date_range: 'Presente', description: 'Docente en el programa de Computación e Informática (DSI). Formación de estudiantes en tecnologías de la información, programación y gestión de sistemas. (Plaza: 1145002 - Pausa, Ayacucho)', icon_key: 'book', color_key: 'blue', sort_order: 1, is_active: true },
      { role: 'Desarrollador Mobile & AI (Freelance)', company: 'Proyectos Independientes', date_range: '2023 – Presente', description: 'Desarrollo, publicación y monetización de aplicaciones en Google Play Store. Creación de Papa Scan (detección de enfermedades con IA) y CIE-10 (consulta de códigos médicos).', icon_key: 'laptop', color_key: 'purple', sort_order: 2, is_active: true },
      { role: 'Técnico de Soporte y Redes', company: 'SETELSAT Consulting', date_range: 'Ene 2023 – Dic 2023', description: 'Mantenimiento preventivo y correctivo de equipos informáticos, estructuración de redes y soporte técnico especializado a usuarios.', icon_key: 'briefcase', color_key: 'emerald', sort_order: 3, is_active: true },
      { role: 'Soporte y Digitador SIS', company: 'DISA Apurímac II', date_range: 'Mar 2022 – Jul 2023', description: 'Gestión de sistemas de información en salud, digitación de formatos SIS, y soporte técnico a los equipos de la Dirección de Salud.', icon_key: 'activity', color_key: 'amber', sort_order: 4, is_active: true },
    ]);
    if (e3) console.error('  ❌ Error insertando experiencias:', e3.message);
    else console.log('  ✅ 4 experiencias insertadas');
  } else {
    console.log('  ⏭️  Experiencias ya existen, saltando seed');
  }

  // 4. Seed skills
  console.log('🌱 Insertando habilidades...');
  const { data: existingSkills } = await supabase.from('skills').select('id').limit(1);
  if (existingSkills && existingSkills.length === 0) {
    const { error: e4 } = await supabase.from('skills').insert([
      { category: 'Frontend & Web',  icon_key: 'code2',      color_key: 'blue',   items: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript'], sort_order: 1 },
      { category: 'Mobile',          icon_key: 'smartphone', color_key: 'green',  items: ['Android', 'Kotlin', 'Java', 'Flutter'],            sort_order: 2 },
      { category: 'Backend & DB',    icon_key: 'database',   color_key: 'purple', items: ['Supabase', 'Node.js', 'SQL', 'Oracle'],             sort_order: 3 },
      { category: 'IA & Core',       icon_key: 'brain',      color_key: 'rose',   items: ['TensorFlow Lite', 'MediaPipe', 'Python'],           sort_order: 4 },
      { category: 'Infra & Redes',   icon_key: 'server',     color_key: 'amber',  items: ['Linux Kernel', 'CCNAv7', 'Git', 'Vercel'],          sort_order: 5 },
    ]);
    if (e4) console.error('  ❌ Error insertando skills:', e4.message);
    else console.log('  ✅ 5 categorías de skills insertadas');
  } else {
    console.log('  ⏭️  Skills ya existen, saltando seed');
  }

  console.log('\n✅ Migración completa. Verifica tu Supabase Dashboard.');
}

runMigration().catch(console.error);
