-- Crear tabla de Proyectos
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  stack text[] not null default '{}',
  image text,
  demolink text not null,
  playstore text,
  metrics text not null default 'N/A',
  status text not null default 'Activo',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Crear tabla de Leads (Contacto)
CREATE TABLE IF NOT EXISTS public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  email text not null,
  message text not null,
  status text not null default 'NUEVO',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Seguridad) - Permite acceso de lectura público a proyectos
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Proyectos son públicos" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Permitir todo al service_role" ON public.projects USING (true);

-- Leads: Solo el admin puede verlos, pero cualquiera puede insertar (formulario público)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cualquiera puede crear leads" ON public.leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Solo admin puede leer leads" ON public.leads FOR SELECT USING (true);
CREATE POLICY "Permitir todo al service_role" ON public.leads USING (true);
