-- 1. Tabla de Proyectos (Portafolio)
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  metrics TEXT NOT NULL,
  description TEXT NOT NULL,
  stack TEXT[] NOT NULL,
  image TEXT NOT NULL,
  demoLink TEXT,
  playStore TEXT,
  status TEXT NOT NULL,
  theme_config JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Configuración del Sitio (Theme Builder)
CREATE TABLE site_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  primary_color TEXT DEFAULT '#2563eb',
  secondary_color TEXT DEFAULT '#1e40af',
  hero_title TEXT DEFAULT 'Percy Acha',
  hero_subtitle TEXT DEFAULT '@ATPDEV',
  hero_typewriter TEXT[] DEFAULT ARRAY['Android Developer', 'Web Engineer', 'AI Integrator', 'Freelancer'],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Datos Personales (Perfil iPortfolio)
CREATE TABLE profile_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT DEFAULT 'Percy Acha',
  birth_date TEXT DEFAULT '14 Nov 1995',
  phone TEXT DEFAULT '+51 987 654 321',
  city TEXT DEFAULT 'Lima, Perú',
  age INT DEFAULT 28,
  degree TEXT DEFAULT 'Ingeniero de Software',
  email TEXT DEFAULT 'contacto@atpdev.dev',
  freelance_status TEXT DEFAULT 'Disponible',
  bio_short TEXT DEFAULT 'Desarrollador Full Stack y Mobile con experiencia en la creación de aplicaciones nativas en Android y plataformas web modernas.',
  bio_long TEXT DEFAULT 'A lo largo de mi carrera, he liderado el desarrollo de productos desde la concepción hasta el despliegue en producción.',
  stats_clients INT DEFAULT 15,
  stats_projects INT DEFAULT 42,
  stats_hours INT DEFAULT 2500,
  stats_students INT DEFAULT 100,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insertar valores iniciales (Semilla / Seed) para que la página no esté vacía al conectarse.
INSERT INTO site_config (id) VALUES (1);
INSERT INTO profile_data (id) VALUES (1);

-- Insertar los 3 proyectos base de muestra
INSERT INTO projects (title, category, metrics, description, stack, image, demoLink, playStore, status) VALUES 
('ChannelsTV', 'Android Apps', '100k+ Descargas', 'App de Streaming en Android con arquitectura limpia, Room y suscripciones integradas (Google Play Billing).', ARRAY['Kotlin', 'Jetpack Compose', 'Hilt', 'Room'], '/assets/img/portfolio/app-1.jpg', '#', 'https://play.google.com', 'En Producción'),
('Almaniq Content Pipeline', 'IA & Bots', '50+ Videos Mensuales', 'Automatización de videos cortos con IA de extremo a extremo, desde curación de guiones hasta publicación directa en redes.', ARRAY['Node.js', 'Meta AI', 'Puppeteer', 'Supabase'], '/assets/img/portfolio/product-1.jpg', '#', NULL, 'Privado'),
('Lector QR Pro', 'Android Apps', '50k+ Usuarios', 'Lector y generador de QRs con modelo freemium, monetizado mediante AdMob y compras in-app.', ARRAY['Kotlin', 'MVVM', 'Coroutines'], '/assets/img/portfolio/branding-1.jpg', '#', 'https://play.google.com', 'En Producción');

-- Políticas de Seguridad (Para que el frontend pueda leer y el admin editar)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lectura publica de proyectos" ON projects FOR SELECT USING (true);
CREATE POLICY "Lectura publica de configuracion" ON site_config FOR SELECT USING (true);
CREATE POLICY "Lectura publica de perfil" ON profile_data FOR SELECT USING (true);

-- Aquí asumimos que las escrituras las haremos ignorando las RLS desde el servidor (Next.js server-side) usando el `service_role` (Secret Key).
